---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autofix_prs: true
  skip:
    - ggshield
    - poetry-lock

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-docstring-first
      - id: name-tests-test
        args:
          - "--pytest-test-first"
      - id: no-commit-to-branch

  - repo: https://github.com/python-poetry/poetry
    rev: "1.4.0"
    hooks:
      - id: poetry-check
      - id: poetry-lock

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/gitguardian/ggshield
    rev: v1.14.4
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
